/*
 * Itur © 2025 by Max Noé <code@itur.cat>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package cat.itur.app.core.datastore

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

private const val TAG = "AndroidKeystoreEmailCipher"

private const val ANDROID_KEYSTORE = "AndroidKeyStore"
private const val KEY_ALIAS = "itur_datastore_email_key"
private const val TRANSFORMATION = "AES/GCM/NoPadding"
private const val GCM_TAG_LENGTH_BITS = 128
private const val GCM_IV_LENGTH_BYTES = 12

/**
 * [EmailCipher] backed by an AES-256-GCM key generated inside the Android Keystore
 * (`setBlockModes`/`setEncryptionPaddings` mean the raw key material never leaves hardware- or
 * software-backed keystore isolation, unlike a key derived and held in process memory). The
 * on-disk [IturPreferencesDataStore] file therefore holds ciphertext, not a plaintext email,
 * if extracted via `adb backup` or on a rooted device.
 *
 * Stored form is `base64(iv || ciphertext)`; the 12-byte GCM IV is regenerated by the keystore
 * on every [encrypt] call and does not need to be secret, only recorded alongside its ciphertext.
 */
internal class AndroidKeystoreEmailCipher : EmailCipher {

    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keyStore.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }

        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE).apply {
            init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .build(),
            )
        }.generateKey()
    }

    override fun encrypt(plainText: String): String {
        if (plainText.isEmpty()) return ""
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.ENCRYPT_MODE, secretKey())
        }
        val ciphertext = cipher.doFinal(plainText.toByteArray(Charsets.UTF_8))
        return Base64.encodeToString(cipher.iv + ciphertext, Base64.NO_WRAP)
    }

    /**
     * Returns "" if [storedValue] can't be decrypted with this device's current Keystore key.
     * The key is device-bound and deliberately excluded from Android backup/device-transfer
     * (see `AOSS-E65B`), so a value restored from another device's backup is undecryptable by
     * design, not corrupt -- there is no key to recover it with. Treating that the same as "no
     * email set" is the only recoverable outcome; the alternative is crashing on first read.
     */
    override fun decrypt(storedValue: String): String {
        if (storedValue.isEmpty()) return ""
        return try {
            val combined = Base64.decode(storedValue, Base64.NO_WRAP)
            val iv = combined.copyOfRange(0, GCM_IV_LENGTH_BYTES)
            val ciphertext = combined.copyOfRange(GCM_IV_LENGTH_BYTES, combined.size)
            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv))
            }
            String(cipher.doFinal(ciphertext), Charsets.UTF_8)
        } catch (exception: GeneralSecurityException) {
            Log.w(TAG, "Stored email is undecryptable with this device's Keystore key; treating as unset.", exception)
            ""
        } catch (exception: IllegalArgumentException) {
            Log.w(TAG, "Stored email is not valid base64; treating as unset.", exception)
            ""
        }
    }
}
