/*
 * Itur © 2025 by Max Noé <code@itur.cat>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package cat.itur.app.core.datastore

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

private const val TAG = "AndroidKeystoreEmailCipher"

private const val ANDROID_KEYSTORE = "AndroidKeyStore"
private const val CURRENT_KEY_ALIAS = "itur_datastore_email_key_aes256_v2"
private const val LEGACY_KEY_ALIAS = "itur_datastore_email_key"
private const val CURRENT_CIPHERTEXT_PREFIX = "aes256-gcm:v2:"
private const val TRANSFORMATION = "AES/GCM/NoPadding"
private const val KEY_SIZE_BITS = 256
private const val GCM_TAG_LENGTH_BITS = 128
private const val GCM_IV_LENGTH_BYTES = 12

/**
 * [EmailCipher] backed by an AES-256-GCM key generated inside the Android Keystore
 * (`setBlockModes`/`setEncryptionPaddings` mean the raw key material never leaves hardware- or
 * software-backed keystore isolation, unlike a key derived and held in process memory). The
 * on-disk [IturPreferencesDataStore] file therefore holds ciphertext, not a plaintext email,
 * if extracted via `adb backup` or on a rooted device.
 *
 * Stored form is `aes256-gcm:v2:base64(iv || ciphertext)`; the 12-byte GCM IV is regenerated by
 * the keystore on every [encrypt] call and does not need to be secret, only recorded alongside
 * its ciphertext. The prefix lets startup migration distinguish ciphertext from values written
 * by app versions that stored the email as plaintext.
 */
internal class AndroidKeystoreEmailCipher(
    currentKeyAlias: String = CURRENT_KEY_ALIAS,
    legacyKeyAlias: String = LEGACY_KEY_ALIAS,
) : EmailCipher,
    StoredEmailMigration {
    private val emailKeyStore = AndroidEmailKeyStore(currentKeyAlias, legacyKeyAlias)

    override fun encrypt(plainText: String): String {
        if (plainText.isEmpty()) return ""
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.ENCRYPT_MODE, emailKeyStore.currentKey())
        }
        val ciphertext = cipher.doFinal(plainText.toByteArray(Charsets.UTF_8))
        return CURRENT_CIPHERTEXT_PREFIX + Base64.encodeToString(cipher.iv + ciphertext, Base64.NO_WRAP)
    }

    /**
     * Returns "" if [storedValue] can't be decrypted with this device's current Keystore key.
     * The key is device-bound and deliberately excluded from Android backup/device-transfer
     * (see `AOSS-E65B`), so a value restored from another device's backup is undecryptable by
     * design, not corrupt -- there is no key to recover it with. Treating that the same as "no
     * email set" is the only recoverable outcome; the alternative is crashing on first read.
     */
    override fun decrypt(storedValue: String): String = when {
        storedValue.isEmpty() -> ""
        !storedValue.startsWith(CURRENT_CIPHERTEXT_PREFIX) -> {
            Log.w(TAG, "Stored email has not completed encryption migration; treating as unset.")
            ""
        }
        else -> decryptCurrentCiphertext(storedValue)
    }

    private fun decryptCurrentCiphertext(storedValue: String): String = try {
        decryptWithKey(
            storedValue.removePrefix(CURRENT_CIPHERTEXT_PREFIX),
            emailKeyStore.currentKey(),
        )
    } catch (exception: GeneralSecurityException) {
        Log.w(TAG, "Stored email is undecryptable with this device's Keystore key; treating as unset.", exception)
        ""
    } catch (exception: IllegalArgumentException) {
        Log.w(TAG, "Stored email is not valid base64; treating as unset.", exception)
        ""
    }

    override fun shouldMigrate(storedValue: String): Boolean {
        val usesLegacyFormat = storedValue.isNotEmpty() &&
            !storedValue.startsWith(CURRENT_CIPHERTEXT_PREFIX)
        return usesLegacyFormat || emailKeyStore.hasLegacyKey()
    }

    override fun migrate(storedValue: String): String = when {
        storedValue.isEmpty() || storedValue.startsWith(CURRENT_CIPHERTEXT_PREFIX) -> storedValue
        else -> migrateLegacyValue(storedValue)
    }

    private fun migrateLegacyValue(storedValue: String): String {
        val legacyPlainText = decryptLegacyCiphertext(storedValue)
        return when {
            legacyPlainText != null -> encrypt(legacyPlainText)
            storedValue.isLegacyPlaintextEmail() -> encrypt(storedValue)
            else -> {
                Log.w(TAG, "Legacy stored email is neither readable ciphertext nor plaintext; removing it.")
                ""
            }
        }
    }

    override fun cleanUp() = emailKeyStore.deleteLegacyKey()

    private fun decryptLegacyCiphertext(storedValue: String): String? = if (!emailKeyStore.hasLegacyKey()) {
        null
    } else {
        val legacyKey = emailKeyStore.legacyKey()
        if (legacyKey == null) {
            null
        } else {
            try {
                decryptWithKey(storedValue, legacyKey)
            } catch (exception: GeneralSecurityException) {
                Log.w(TAG, "Legacy ciphertext cannot be decrypted; it will be removed.", exception)
                null
            } catch (exception: IllegalArgumentException) {
                Log.d(TAG, "Legacy stored email is not encoded as ciphertext.", exception)
                null
            }
        }
    }

    private fun decryptWithKey(encodedCiphertext: String, key: SecretKey): String {
        val combined = Base64.decode(encodedCiphertext, Base64.NO_WRAP)
        require(combined.size > GCM_IV_LENGTH_BYTES) { "Ciphertext does not contain an authentication tag." }
        val iv = combined.copyOfRange(0, GCM_IV_LENGTH_BYTES)
        val ciphertext = combined.copyOfRange(GCM_IV_LENGTH_BYTES, combined.size)
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv))
        }
        return String(cipher.doFinal(ciphertext), Charsets.UTF_8)
    }

    private fun String.isLegacyPlaintextEmail(): Boolean {
        val separator = indexOf('@')
        return separator > 0 && separator < lastIndex
    }
}

private class AndroidEmailKeyStore(
    private val currentKeyAlias: String,
    private val legacyKeyAlias: String,
) {
    fun currentKey(): SecretKey {
        val keyStore = loadKeyStore()
        (keyStore.getKey(currentKeyAlias, null) as? SecretKey)?.let { return it }

        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE).apply {
            init(
                KeyGenParameterSpec.Builder(
                    currentKeyAlias,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                )
                    .setKeySize(KEY_SIZE_BITS)
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .build(),
            )
        }.generateKey()
    }

    fun hasLegacyKey(): Boolean = legacyKeyAlias != currentKeyAlias && loadKeyStore().containsAlias(legacyKeyAlias)

    fun legacyKey(): SecretKey? = loadKeyStore().getKey(legacyKeyAlias, null) as? SecretKey

    fun deleteLegacyKey() {
        if (legacyKeyAlias == currentKeyAlias) return
        loadKeyStore().apply {
            if (containsAlias(legacyKeyAlias)) deleteEntry(legacyKeyAlias)
        }
    }

    private fun loadKeyStore(): KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
}
